### ISSUE TITLE
🐞 Unlocking FLP does not work.

### ISSUE THREAD

**Issue by prolexgreen** [demberto/PyFLP#140]
### Describe the issue

The FLP does not work when ran with code. It does gen a new FLP but it is still in trial mode.

### What version of PyFLP are you using?

2.1.0

### What code caused this issue?
```py
import pyflp

project = pyflp.parse(r"C:\Users\coolb\Downloads\Project_4\Project_4 - Copy.flp")

# Unlock the FLP itself
project.registered = True

# Unlock trial version native plugins
for instument in project.channels.instruments:
    instrument.demo_mode = False

for insert in project.mixer:
    for slot in insert:
        if slot.plugin is not None:
            slot.plugin.demo_mode = False

pyflp.save(project,r"C:\Users\coolb\Downloads\Project_4\Project_42- Copy.flp")
```

### Screenshots, Additional info

```
PS C:\Users\USER\Downloads\Project_4> python test.py
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\Project_4\test.py", line 9, in <module>
    for instument in project.channels.instruments:
  File "C:\Users\USER\anaconda3\lib\site-packages\pyflp\channel.py", line 1651, in instruments
    yield from (ch for ch in self if isinstance(ch, Instrument))
  File "C:\Users\USER\anaconda3\lib\site-packages\pyflp\channel.py", line 1651, in <genexpr>
    yield from (ch for ch in self if isinstance(ch, Instrument))
  File "C:\Users\USER\anaconda3\lib\site-packages\pyflp\channel.py", line 1619, in __iter__
    cur_ch = ch_dict[iid] = ct(et, channels=ch_dict, group=groups[groupnum])
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
Send the project file. I need to analyse it.

**Comment by prolexgreen** [comment]
ok
[Project_4 - Copy (2).zip](https://github.com/demberto/PyFLP/files/11446598/Project_4.-.Copy.2.zip)
I had to change the filename, just rename the end to .flp

**Comment by prolexgreen** [comment]
could you unlock it and send it back?

**Comment by prolexgreen** [comment]
Demberto is there any quick fix?

**Comment by demberto** [comment]
Uh nope. See #146 for details. Until I or hopefully someone figures out how values are encoded in FL 21 projects, I see no way.

**Comment by prolexgreen** [comment]
Any fixes found?
Thanks!
