### ISSUE TITLE
🐞 Python 3.12 Enum issue

### ISSUE THREAD

**Issue by kingkongjames** [demberto/PyFLP#183]
### Describe the issue

Thats the whole code. When I try to run, this happens:

Traceback (most recent call last):
  File "C:\Users\Stefan\PycharmProjects\fl_changer\main.py", line 6, in <module>
    project = pyflp.parse("res/beat.flp")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\PycharmProjects\fl_changer\venv\Lib\site-packages\pyflp\__init__.py", line 123, in parse
    id = EventEnum(int.from_bytes(stream.read(1), "little"))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefan\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 744, in __call__
    raise TypeError(
TypeError: <enum 'EventEnum'> has no members; specify `names=()` if you meant to create a new, empty, enum

What does that mean?
Thank you.

### What version of PyFLP are you using?

2.2.1

### What code caused this issue?

```python3
import pathlib
import sys
import pyflp
project = pyflp.parse("res/beat.flp")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
Hmm, I haven't tested PyFLP on Python 3.12 yet. It's difficult for me to find time for this nowadays.

**Comment by Robatortas** [comment]
The same issue reproduces on my project too.

**Comment by SilverShepherd** [comment]
I have the same issue

**Comment by Mister-SOSA** [comment]
Same issue here as well

**Comment by Bigmancozmo** [comment]
Same issue here, but on Python 3.11.9.

**Comment by Lilicogamer13** [comment]
same issue here, but in all python 3 versions(like, littery, all the starting with 3 versions that is here https://www.python.org/doc/versions/), but only in windows

**Comment by bartvanandel** [comment]
The problem persists on MacOS as well. I've tried it with a stock template file, using Python 3.12.7:

```py
import pyflp as flp
p = flp.parse('/Applications/Audio/FL Studio 2024.app/Contents/Resources/FL/Data/Templates/Advanced/Electronic/Drum & Bass.flp')
```

Different paths, same error.

**Comment by naweka** [comment]
Same error, python 3.12.7

**Comment by naweka** [comment]
fast dirty fix: 
![image](https://github.com/user-attachments/assets/21889c3b-08fa-4f7d-b1d7-598d6a93929b)

![image](https://github.com/user-attachments/assets/38dce6f7-97e4-49e2-991b-45dbdba530a6)


![image](https://github.com/user-attachments/assets/2be78822-109e-427e-a848-691629a847fa)

**Comment by MichaelTen** [comment]
thanks @naweka that worked! 

I created a pull request to do conditional usage of your "dirty fix" https://github.com/demberto/PyFLP/pull/196 (merge at not my risk - i did not test it - i just implemented the "dirty fix" directly for my usage.)

i also created a mini project to extra sample file paths in the case where they cannot be located and unfortunately FL Studio does not have a built in easy peasy way of seeing where FL Studio thinks the samples are (so they can be moved there or whatever to get the FL Studio project to load OK)

https://github.com/MichaelTen/FL-Studio-file-path-extractor

for anyone curious to implement the "dirty fix" .... use command "pip show pyflp" to see where the actually files are located to directly edit them.

**Comment by Windows81** [comment]
For a cleaner fix, I'd look into https://github.com/python/cpython/issues/114474.

**Comment by ancientstraits** [comment]
What would it require in order to resolve this issue correctly?

**Comment by Windows81** [comment]
@ancientstraits: it would require the original dev eloper to take any of our proposed fixes and merge them to the project.

**Comment by Lilicogamer13** [comment]
holy vibecoded

**Comment by westclox-star** [comment]
fixed it on my fork and made a pr for this. https://github.com/westclox-star/FLPy
